ALGOLIASEARCH_APPLICATION_ID: YourApplicationID
ALGOLIASEARCH_API_KEY: YourAPIKey
ALGOLIASEARCH_API_KEY_RO: ASearchOnlyAPIKey
NEW_RELIC_LICENSE_KEY: newreliclicensekey
NEW_RELIC_APP_NAME: newrelicappname