ALGOLIASEARCH_APPLICATION_ID: YourApplicationID
ALGOLIASEARCH_API_KEY: YourAPIKey
ALGOLIASEARCH_API_KEY_RO: ASearchOnlyAPIKey
AMAZON_ACCESS_KEY_ID: s3accesskeyid
AMAZON_SECRET_ACCESS_KEY: s3secretaccesskey
HN_SECRET_REALTIME_EXPORT_URL: thatsoursecretsauce
