ADMIN_USER: admin
ADMIN_PASSWORD: 1234
ALGOLIASEARCH_APPLICATION_ID: YourApplicationID
ALGOLIASEARCH_API_KEY: YourAPIKey
ALGOLIASEARCH_API_KEY_RO: ASearchOnlyAPIKey
AMAZON_ACCESS_KEY_ID: s3accesskeyid
AMAZON_SECRET_ACCESS_KEY: s3secretaccesskey
HN_SECRET_REALTIME_EXPORT_ITEM_URL: thatsoursecretsauce
HN_SECRET_REALTIME_EXPORT_USER_URL: thatsoursecretsauce
KIMONOLABS_API_KEY: kimonoapikey
